server:
  error:
    whitelabel:
      enabled: false
spring:
  profiles:
    active: development
  r2dbc:
    # MySQL
    url: 'r2dbc:mysql://localhost:3306/twig'
    username: 'twig'
    password: 'twig'
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ae9a0ded1a9173830878
            clientSecret: a01a8046cdec11dca178de6fa946facc786d9405

sentry:
  dsn: 'https://4a1d7adfa01f42ecad6092d0f3cd8466@o759320.ingest.sentry.io/5792476'

twig:
  enableDatabaseSetup: false
  showInternalServerError: true
  enableRedisCleanup: false
  frontendDistDirectory: './frontend/dist/'

streams:
  url:
    key: urlstream
    group: inApp
