CREATE TABLE IF NOT EXISTS user (id SERIAL PRIMARY KEY, first_name VARCHAR(255), last_name VARCHAR(255));
CREATE TABLE IF NOT EXISTS bookmark (id SERIAL PRIMARY KEY, hostname VARCHAR(1024), uri VARCHAR(1024), protocol VARCHAR(255));
